#
# Basic example for executing an OWASP dependency scan against an application
# built with Microsoft's .NET platform, and failing if any low-severity
# vulnerabilities are found.
#
# This scan configuration will:
# - Execute against the default .NET build output directory.
# - Generate a JSON vulnerability report.
# - Add a comment to the triggering pull request with a summary.
# - Upload the generated report as a workflow artifact for 30 days.
# - Fail the job if any low-severity vulnerabilities are found.
#
name: Low-Severity Failure Example

on:
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“š Checkout
        uses: actions/checkout@v2

      - name: ðŸ”¨ Build w/ .NET      
        run: dotnet build --configuration Release

      - name: âš”ï¸ OWASP
        uses: morrro01/owasp-dependency-scan-action-lnrsg@v1
        with:
          project: 'My Application'
          path: '.'
          format: 'JSON'
          scan_args: >
            --failOnCVSS 7
            --enableRetired
          failure_mode: 'low'